### ISSUE TITLE
Meet with Joe

### ISSUE THREAD

**Issue by Kahuna915** [Kahuna915/Capstone-Design#17]
For this card team members will meet with Joe to discuss their part and or the overall project for the rest of the semester. 

- [x] Noah, Thursday October 27th
- [x] Tanner, Thursday October 27th

**Comment by Kahuna915** [comment]
Noah:
Met with Joe:
Discussed, AWS accounts and why I can't delete them, was the problem I had will be testing perms/access groups I set up. Talked about automating account creation with AWS CLI. Discussed what the Client wants for Demo2. Next steps are to test the account perms I created in Demo1 on full AWS accounts and not iam users. Then create the AWS CLI script to automate that creation. As for other things, will be meeting with Devin regarding cyber.local config.

**Comment by TannerWeinacker** [comment]
Tanner:
Met with Joe:
Discussed potentially using a read-only domain controller in the cloud. This would provide a smooth transition of permissions and benefits of on-prem DNS, as well as being secure. Since this is a read-only domain controller, there would be no management or changes that could be done from the cloud side. We also discussed segmenting out the classes. Potentially having the availability for students to have access to AWS for any class as well as class-specific access. Lastly, we spoke about how the students would access their VMS and if they were to be solely on AWS or a mix between AWS and vCenter.
